# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/search_similar_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        self.SearchHelpBtn = QtWidgets.QPushButton(Dialog)
        self.SearchHelpBtn.setGeometry(QtCore.QRect(40, 40, 75, 75))
        self.SearchHelpBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\images/QuestionMark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchHelpBtn.setIcon(icon)
        self.SearchHelpBtn.setIconSize(QtCore.QSize(48, 48))
        self.SearchHelpBtn.setObjectName("SearchHelpBtn")
        self.SearchHomeBtn = QtWidgets.QPushButton(Dialog)
        self.SearchHomeBtn.setGeometry(QtCore.QRect(680, 40, 75, 75))
        self.SearchHomeBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui\\images/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchHomeBtn.setIcon(icon1)
        self.SearchHomeBtn.setIconSize(QtCore.QSize(48, 48))
        self.SearchHomeBtn.setObjectName("SearchHomeBtn")
        self.SearchTitleMsg = QtWidgets.QTextBrowser(Dialog)
        self.SearchTitleMsg.setGeometry(QtCore.QRect(290, 155, 220, 60))
        self.SearchTitleMsg.setObjectName("SearchTitleMsg")
        self.SearchBox = QtWidgets.QLineEdit(Dialog)
        self.SearchBox.setGeometry(QtCore.QRect(250, 260, 300, 70))
        self.SearchBox.setAlignment(QtCore.Qt.AlignCenter)
        self.SearchBox.setClearButtonEnabled(True)
        self.SearchBox.setObjectName("SearchBox")
        self.SearchSearchBtn = QtWidgets.QPushButton(Dialog)
        self.SearchSearchBtn.setGeometry(QtCore.QRect(362, 430, 75, 75))
        self.SearchSearchBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ui\\images/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchSearchBtn.setIcon(icon2)
        self.SearchSearchBtn.setIconSize(QtCore.QSize(48, 48))
        self.SearchSearchBtn.setObjectName("SearchSearchBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SearchTitleMsg.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Enter a book you like to</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">see recommendations</span></p></body></html>"))
        self.SearchBox.setPlaceholderText(_translate("Dialog", "Enter title here"))
